version: '3.2'

services:
  jvm:
    image: docker.io/ivanpopov/chat-gpt-bot:latest
    depends_on:
      - db
    ports:
      - 80:8080
    env_file:
      - .env
    command:
      - java -jar build/libs/bot-0.0.1.jar
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db:
