spring:
  application.name: gpt4Bot
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create
#        jdbc:
#          lob:
#            non_contextual_creation: true
