name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deployment:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: get docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: 22
          script: |
            docker pull docker.io/${{ vars.DOCKER_IMAGE_NAME }}:latest
